apiVersion: prow.k8s.io/v1
kind: ProwJob
metadata:
  annotations:
    prow.k8s.io/context: builder-base-tooling-postsubmit
    prow.k8s.io/job: builder-base-tooling-postsubmit
  creationTimestamp: null
  labels:
    created-by-prow: "true"
    event-GUID: e2ff0f28-54a2-11ed-9f20-44b1648473e3
    image-build: "true"
    pr-creation: "true"
    prow.k8s.io/build-id: "1585004146891689984"
    prow.k8s.io/context: builder-base-tooling-postsubmit
    prow.k8s.io/id: e46cea28-54a2-11ed-b396-22bcd61f53ac
    prow.k8s.io/job: builder-base-tooling-postsubmit
    prow.k8s.io/refs.base_ref: main
    prow.k8s.io/refs.org: aws
    prow.k8s.io/refs.repo: eks-distro-build-tooling
    prow.k8s.io/type: postsubmit
  name: 2bddab1e-561c-11ed-af82-0a1b7c86eaa0
spec:
  agent: kubernetes
  cluster: prow-postsubmits-cluster
  context: builder-base-tooling-postsubmit
  decoration_config:
    gcs_configuration:
      bucket: s3://prowdataclusterstack-316434458-prowbucket7c73355c-1n9f9v93wpjcm
      path_strategy: explicit
    s3_credentials_secret: s3-credentials
    utility_images:
      clonerefs: public.ecr.aws/eks-distro-build-tooling/prow-clonerefs:v20220727-a57f8abeb4
      entrypoint: public.ecr.aws/eks-distro-build-tooling/prow-entrypoint:v20220727-a57f8abeb4
      initupload: public.ecr.aws/eks-distro-build-tooling/prow-initupload:v20220727-a57f8abeb4
      sidecar: public.ecr.aws/eks-distro-build-tooling/prow-sidecar:v20220727-a57f8abeb4
  error_on_eviction: true
  extra_refs:
    - base_ref: main
      org: eks-distro-pr-bot
      repo: eks-distro-prow-jobs
    - base_ref: main
      org: eks-distro-pr-bot
      repo: eks-anywhere-prow-jobs
  job: builder-base-tooling-postsubmit
  max_concurrency: 10
  namespace: default
  pod_spec:
    automountServiceAccountToken: false
    containers:
      - command:
          - bash
          - -c
          - |
            trap 'touch /status/done' EXIT && scripts/buildkit_check.sh && source scripts/setup_public_ecr_push.sh && make release -C builder-base IMAGE_TAG=$PULL_BASE_SHA.${AL_TAG}
        env:
          - name: AL_TAG
            value: "2"
          - name: IMAGE_REPO
            value: public.ecr.aws/eks-distro-build-tooling
          - name: ECR_PUBLIC_PUSH_ROLE_ARN
            value: arn:aws:iam::832188789588:role/ECRPublicPushRole
          - name: AWS_REGION
            value: us-east-1
          - name: AWS_SDK_LOAD_CONFIG
            value: "true"
          - name: AWS_ROLE_SESSION_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: GOPROXY
            value: http://athens-proxy.default.svc.cluster.local
        image: public.ecr.aws/eks-distro-build-tooling/builder-base:9242630ce031e03158c65753c07bbfc79985347e.2
        name: build-container
        resources:
          requests:
            cpu: "4"
            memory: 16Gi
        volumeMounts:
          - mountPath: /secrets/github-secrets
            name: github-auth
            readOnly: true
          - mountPath: /secrets/ssh-secrets
            name: ssh-auth
            readOnly: true
          - mountPath: /root/.docker/config.json
            name: docker-registry-config
            subPath: config.json
          - mountPath: /run/buildkit
            name: run-buildkit
          - mountPath: /script
            name: entrypoint
          - mountPath: /status
            name: status
          - mountPath: /config
            name: builder-base-tag-file
      - args:
          - /script/entrypoint.sh
        command:
          - sh
        env:
          - name: AWS_SDK_LOAD_CONFIG
            value: "true"
          - name: AWS_ROLE_SESSION_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: GOPROXY
            value: http://athens-proxy.default.svc.cluster.local
        image: moby/buildkit:v0.10.1-rootless
        name: buildkitd
        resources:
          requests:
            cpu: 1024m
            memory: 2Gi
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
        volumeMounts:
          - mountPath: /secrets/github-secrets
            name: github-auth
            readOnly: true
          - mountPath: /secrets/ssh-secrets
            name: ssh-auth
            readOnly: true
          - mountPath: /root/.docker/config.json
            name: docker-registry-config
            subPath: config.json
          - mountPath: /run/buildkit
            name: run-buildkit
          - mountPath: /script
            name: entrypoint
          - mountPath: /status
            name: status
          - mountPath: /config
            name: builder-base-tag-file
    nodeSelector:
      arch: AMD64
    serviceAccountName: postsubmits-build-account
    volumes:
      - name: github-auth
        secret:
          defaultMode: 256
          secretName: pr-bot-github-token
      - name: ssh-auth
        secret:
          defaultMode: 256
          secretName: pr-bot-ssh-secret
      - configMap:
          items:
            - key: docker-ecr-config.json
              path: config.json
          name: build-setup
        name: docker-registry-config
      - configMap:
          items:
            - key: buildkitd-entrypoint.sh
              path: entrypoint.sh
          name: buildkitd-entrypoint
        name: entrypoint
      - emptyDir: {}
        name: run-buildkit
      - emptyDir: {}
        name: status
      - configMap:
          items:
            - key: BUILDER_BASE_TAG_FILE
              path: BUILDER_BASE_TAG_FILE
          name: builder-base-tag-file
        name: builder-base-tag-file
  prowjob_defaults:
    tenant_id: GlobalDefaultID
  refs:
    base_link: https://github.com/aws/eks-distro-build-tooling/compare/56732c53184a...7e3154406cdf
    base_ref: main
    base_sha: 7e3154406cdf70dbe7b2fd87d5e7a48dd2014b9d
    org: aws
    repo: eks-distro-build-tooling
    repo_link: https://github.com/aws/eks-distro-build-tooling
  report: true
  type: postsubmit
status:
  startTime: "2022-10-27T17:24:11Z"
  state: triggered